<?php
return [
	'adjectives' => [
		'accelerated',
		'accessible',
		'acoustic',
		'active',
		'activation',
		'activated',
		'actuator',
		'adapted',
		'adhesive',
		'adjustable',
		'advanced',
		'aerial',
		'aerodynamic',
		'aeronautic',
		'aeronautical',
		'aerospace',
		'aggregated',
		'alpha',
		'allotropic',
		'alloy',
		'alternative',
		'ambient',
		'amplified',
		'analog',
		'angular',
		'anionic',
		'annealed',
		'anodized',
		'apex',
		'applied',
		'armature',
		'articulated',
		'assembled',
		'assembler',
		'associated',
		'astronautic',
		'astronautical',
		'asymmetric',
		'asynchronous',
		'atmospheric',
		'atomic',
		'automatic',
		'automation',
		'autothermic',
		'auxiliary',
		'avionic',
		'aviation',
		'axial',
	],

	'nouns' => [
		'dampers',
		'data systems',
		'datology',
		'decisions',
		'deployment',
		'deployments',
		'derivatives',
		'developments',
		'developments',
		'devices',
		'dials',
		'diamagnetics',
		'dielectrics',
		'differentials',
		'digital',
		'dihedrals',
		'diodes',
		'directionals',
		'discoveries',
		'discovery',
		'discs',
		'distributions',
		'drafting',
		'dynamics',
		'dynamos',
	],

	'slogans' => [
		'Proving the impossible, possible',
	]
];